root: true

extends:
  - '@pragmatic-divops'
  - '@pragmatic-divops/mocha'
  - '@pragmatic-divops/cucumber'

parserOptions:
  ecmaVersion: 2022

rules:
  import/extensions:
    - warn
    - ignorePackages
